<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$assetRepo = $objectManager->get('Magento\Framework\View\Asset\Repository');
$images_url = $assetRepo->getUrl("RicardoMartins_PagSeguro::images");

$html = "<img src='".$images_url."/visa-large.png' height='35'>\r\n";
$html .= "<img src='".$images_url."/mastercard-large.png' height='35'>\r\n";
$html .= "<img src='".$images_url."/american-express-large.png' height='35'><br>\r\n";
$html .= "<img src='".$images_url."/elo-large.png' height='35'>\r\n";
$html .= "<img src='".$images_url."/diners-club-large.png' height='35'>\r\n";
$html .= "<img src='".$images_url."/hipercard-large.png' height='35'>\r\n";
$html .= "</div>\r\n";

?>
<div id="pagSeguroCcImagesHtml" style="display: none;"><?php echo $html; ?></div>
