<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$assetRepo = $objectManager->get('Magento\Framework\View\Asset\Repository');
$images_url = $assetRepo->getUrl("RicardoMartins_PagSeguro::images");
$enable_cc_images = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('payment/rm_pagseguro_cc/enable_cc_images');
$html = "";
if($enable_cc_images) {
    $html .= "<img style=\"margin-left:27px; height: 35px;\" src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/visa.png') . "\">\r\n";
    $html .= " <img style='height: 35px;' src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/mastercard.png') . "\">\r\n";
    $html .= " <img style='height: 35px;' src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/elo.png') . "\">\r\n";
    $html .= " <img style='height: 35px;' src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/amex.png') . "\">\r\n";
    $html .= " <img style='height: 35px;' src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/diners.png') . "\">\r\n";
    $html .= " <img style='height: 35px;' src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/hipercard.png') . "\">\r\n";
    $html .= "<img style=\"height: 35px;\" src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/outros.png') . "\">\r\n";
    $html .= " <img style='height: 35px;' src=\"" . $this->getViewFileUrl('RicardoMartins_PagSeguro::images/pslogo.png') . "\">\r\n";
//    $html .= "</div>\r\n";
}

?>
<div id="pagSeguroMultiCcImagesHtml" style="display: none;"><?php echo $html; ?></div>
