<?php
$helper = $this->helper('RicardoMartins\PagSeguro\Helper\Data');
$viewJsPath = $block->getViewFileUrl('RicardoMartins_PagSeguro::js/pagseguro.js');
$storeUrl = $helper->getStoreUrl();
$grandTotal = $helper->getGrandTotal();
$installments = $helper->getInstallmentQty();
$visibleCpf = $helper->isCpfVisible() ? '1':'0';
$visibleDob = $helper->isDobVisible() ? '1':'0';
$ccPlaceholderImage = $this->getViewFileUrl('RicardoMartins_PagSeguro::images/cc-placeholder.png');
$isSandbox = $helper->isSandbox() ? 1 : 0;
?>

<script src="<?php echo $viewJsPath;?>"></script>
<script type="text/javascript">
     //<![CDATA[
    function preparePagSeguro(){

        if(typeof RMPagSeguroObj != "undefined"){
            <?php if ($helper->isDebugActive()): ?>
            console.info('PagSeguro was already started.');
            <?php endif; ?>
            return;
        }
        <?php if ($helper->isDebugActive()): ?>
        console.info('PagSeguro is initiating. Wait for ready message.');
        <?php endif; ?>
            var RMPagSeguroObj = new RMPagSeguro(<?php echo $helper->getConfigJs()?>);
            console.info('PagSeguro ready');
            RMPagSeguroObj.addCardFieldsObserver(RMPagSeguroObj);
            RMPagSeguroObj.setStoreUrl("<?php echo $storeUrl ?>");
            RMPagSeguroObj.updateBrand();
            RMPagSeguroObj.setInstallmentsQty(<?php echo $installments;?>);
            RMPagSeguroObj.getGrandTotal();
            RMPagSeguroObj.removeUnavailableBanks();
            RMPagSeguroObj.setCardPlaceHolderImage("<?php echo $ccPlaceholderImage ?>");
    }
    window.visibleCpf = <?php echo $visibleCpf ?>;
    window.visibleDob = <?php echo $visibleDob ?>;
    window.isSandbox = <?php echo $isSandbox ?>;
    //preparePagSeguro();

    //]]>
</script>
<script>
   require.config({
       map: {
           '*': {
               'PagseguroDirectMethod':  '<?php echo $helper->getJsUrl(); ?>'
           }
       }
   });
</script>
<script>
    require([
        'jquery',
        'inputRMMask'
    ], function ($) {
        $( document ).ready(function() {
            //$('.money').mask("#.###.##0,00", {clearIfNotMatch: true,reverse: true});

            $('.money').on('keyup', function(){
                element = jQuery(this);

                console.log(element.name + ':' + element.val());

                var orginalValue = RMPagSeguroObj.getGrandTotal();
                var orderAmount = (orginalValue).toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,');
                orderAmount = orderAmount.replace(/[^0-9]/g, '');
                orderAmount = Number(orderAmount);

                var value = element.val();
                value = value.replace(/[^0-9]/g, '');
                value = Number(value);

                if (value >= orderAmount) {
                    value = orderAmount - 1;
                }

                if (isNaN(value) || value == 0) {
                    value = 1;
                }

                var remaining = orderAmount - value;

                remaining = (remaining / 100).toFixed(2);
                value = (value / 100).toFixed(2);

                if (element.hasClass("first")) {
                    $('.money.second').val(remaining.toString().replace('.', ',')); 
                }
                if (element.hasClass("second")) {
                    $('.money.first').val(remaining.toString().replace('.', ',')); 
                }
                element.val(value.toString().replace('.', ','));
            });
        });
    });
</script>