<div id="installments_external">
<?php
/** @var \RicardoMartins\PagSeguro\Block\Catalog\Product\Installments $block */
echo $block->getInstallmentsText();
?>
</div>
<script type="application/javascript">
requirejs(['jquery', 'underscore'],function($, _){
    let installmentsObj = document.getElementById("ps_installments_max");
    
    if (_.isNull(installmentsObj)) {
        return
    }

    installmentsObj.addEventListener("click", function(event){
        event.preventDefault();
        $('#installments_list').toggle({duration: 500});
    });
});
</script>
