<?php $permissions = $block->getData('permissions'); ?>
<?php if ($permissions->hasAccessToFlushPagSeguroInstallments()): ?>
    <?php $cleanCacheMessage = addslashes(__("Do You really want to clean the installments cache? This action will remove the stored installments information for all products on store.")); ?>
    <?php $cleanCacheUrl = $block->escapeJs($block->getUrl('pseguroadmin/cache/flushProductInstallments')); ?>
    <p>
        <button id="flushPagSeguroInstallments" type="button">
            <?= $block->escapeHtml(__('Flush Product Installments Cache')); ?>
        </button>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
            'onclick',
            'if (confirm(\'' . $cleanCacheMessage . '\')) setLocation(\'' . $cleanCacheUrl . '\')',
            'button#flushPagSeguroInstallments'
        ) ?>
        <span><?= $block->escapeHtml(__('Stored installments from PagSeguro to each product of the store')); ?></span>
    </p>
<?php endif; ?>