<?php
/** @var \RicardoMartins\PagSeguro\Block\Payment\InfoCc $block */
$info = $block->getPaymentInfo();
?>

<p>
    <strong>
        <?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
        <?php if (isset($info['is_sandbox']) && $info['is_sandbox'] == '1') {
            echo $block->escapeHtml(__(' - Ambiente de Testes'));
        } ?>
    </strong>
</p>
<?php if (isset($info['transaction_id_first']) && isset($info['transaction_id_second'])): ?>
    <p><b>Cartão 1:</b></p>
    <?php if (isset($info['credit_card_type_first'])): ?>
    <p>Bandeira: <?= $block->escapeHtml(ucwords($info['credit_card_type_first'])); ?></p>
    <?php endif?>
    <?php if (isset($info['installment_quantity_first']) && isset($info['installment_value_first'])): ?>
    <p>Parcelas: <?= $block->escapeHtml($info['installment_quantity_first']) ?>
    (R$
        <?= $block->escapeHtml(number_format(str_replace(',', '.', $info['installment_value_first']), 2, ',', '.')) ?>
    )</p>
    <?php endif?>
    <?php if (isset($info['transaction_id_first'])): ?>
        <p>Código da transação do 1º cartão: <?= $block->escapeHtml($info['transaction_id_first']) ?></p>
        <p>
            Status da transação do 1º cartão:
            <b><?= $block->escapeHtml($block->getStatus($info['transaction_id_first'])) ?></b>
        </p>
        <a href="<?= $block->escapeUrl($block->getTransactionLink('first')) ?>" target="_blank">
            <?= $block->escapeHtml(__('View on PagSeguro')) ?>
        </a>
        <br /><br />
    <?php endif?>
    <p><b>Cartão 2:</b></p>
    <?php if (isset($info['credit_card_type_second'])): ?>
    <p>Bandeira: <?= $block->escapeHtml(ucwords($info['credit_card_type_second'])); ?></p>
    <?php endif?>
    <?php if (isset($info['installment_quantity_second']) && isset($info['installment_value_second'])): ?>
    <p>Parcelas: <?= $block->escapeHtml($info['installment_quantity_second']) ?>
    (R$
        <?= $block->escapeHtml(number_format(str_replace(',', '.', $info['installment_value_second']), 2, ',', '.'))?>
    )</p>
    <?php endif?>
    <?php if (isset($info['transaction_id_second'])): ?>
        <p>Código da transação do 2º cartão: <?= $block->escapeHtml($info['transaction_id_second']) ?></p>
        <p>
            Status da transação do 2º cartão:
            <b><?= $block->escapeHtml($block->getStatus($info['transaction_id_second'])) ?></b>
        </p>
        <a href="<?= $block->escapeUrl($block->getTransactionLink('second')) ?>" target="_blank">
            <?= $block->escapeHtml(__('View on PagSeguro')) ?>
        </a>
        <br /><br />
    <?php endif?>
<?php else:?>
    <?php if (isset($info['installment_quantity']) && isset($info['installment_value'])): ?>
    <p>Parcelas: <?= $block->escapeHtml($info['installment_quantity']) ?>
    (R$
        <?= $block->escapeHtml(number_format($info['installment_value'], 2, ',', '.')) ?>
    )</p>
    <?php endif?>
    <?php if (isset($info['transaction_id'])): ?>
        <p>Código da transação: <?= $block->escapeHtml($info['transaction_id']) ?></p>
        <a href="<?= $block->escapeUrl($block->getTransactionLink()) ?>" target="_blank">
            <?= $block->escapeHtml(__('View on PagSeguro')) ?>
        </a>
        <br /><br />
    <?php endif?>
    <?php if (isset($info['escrow_end_date'])) :?>
        <p><a href="javascript: void(0);" onclick="$('ps-extrainfo').toggle()">Exibir/ocultar informações adicionais</a></p>
        <div id="ps-extrainfo" style="font-size: 0.9em; display: none;">
            <p>Taxas: R$ <?=$info['fee_amount']??''?></p>
            <p>Valor líquido: R$ <?=$info['net_amount']??''?></p>
            <?php if (isset($info['escrow_end_date'])):
                $escData = new DateTime($info['escrow_end_date']);?>
                <p>Disponível em: <?=$escData->format('d/m/Y à\s H:i');?> <span title="Data que o valor estará disponível para saque em sua conta PagSeguro" style="font-size: 1.1em; cursor:pointer;">&#x2754</span></p>
            <?php endif;?>
            <p>Tipo do Gateway/Adquirente em: <?=$info['gateway_type']??''?>/<?=$info['gateway_acquirer_name']??''?></p>
            <p>NSU: <?=$info['gateway_nsu']??''?></p>
            <p>TID: <?=$info['gateway_tid']??''?></p>
            <p>Estabilishment Code: <?=$info['gateway_establishment_code']??''?></p>
            <p>Authorization: <?=$info['gateway_authorization_code']??''?></p>
            <p>Raw Code: <?=$info['gateway_raw_code']??''?></p>
            <br/>
        </div>
    <?php endif; ?>
<?php endif;?>

<?= $block->getBlockHtml('pagseguro.actions');
