<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
    <?php foreach ($specificInfo as $label => $value):?>
        <tr>
			<?php if (strpos($value, '<a') == false) { ?>				
				<?php echo '<br />'.implode("\n", $block->getValueAsArray($value, false))  ?>				
			<?php } else { ?>	
            <th><?= $block->escapeHtml($label) ?>:</th>
            <td>
				<?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
            </td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
