<?php /** @var \RicardoMartins\PagSeguro\Block\Payment\Info $block */ ?>
<?php 
$paymentInfo = $block->getPaymentInfo();
$info = $block->getInfo()->getAdditionalInformation();
?>
<p>
    <strong>
        <?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
        <?php if (isset($paymentInfo['is_sandbox']) && $paymentInfo['is_sandbox'] == '1'): ?>
            <?= $block->escapeHtml(__(' - Ambiente de Testes')); ?>
        <?php endif; ?>
    </strong>
</p>
<?php if ($paymentInfo && !isset($info['escrow_end_date'])): ?>
    <p>
        <a href="<?= $block->escapeUrl($paymentInfo['url']); ?>" target="_blank">
            <?= $block->escapeHtml($paymentInfo['texto']);?>
        </a>
        <br />
        <br />
        <a href="<?= $block->escapeUrl($block->getTransactionLink()) ?>" target="_blank">
            <?= $block->escapeHtml(__('View on PagSeguro')) ?>
        </a>
    </p>
<?php endif;?>
    <?php if (isset($info['escrow_end_date'])) :?>
        <p><a href="javascript: void(0);" onclick="$('ps-extrainfo').toggle()">Exibir/ocultar informações adicionais</a></p>
        <div id="ps-extrainfo" style="font-size: 0.9em; display: none;">
            <p>Taxas: R$ <?=$info['fee_amount']??''?></p>
            <p>Valor líquido: R$ <?=$info['net_amount']??''?></p>
            <?php if (isset($info['escrow_end_date'])):
                $escData = new DateTime($info['escrow_end_date']);?>
                <p>Disponível em: <?=$escData->format('d/m/Y à\s H:i');?> <span title="Data que o valor estará disponível para saque em sua conta PagSeguro" style="font-size: 1.1em; cursor:pointer;">&#x2754</span></p>
            <?php endif;?>
            <br/>
        </div>
    <?php endif; ?>
<?= $block->getBlockHtml('pagseguro.actions');
